CFLAGS = -g -Wall -std=c2x

# this is the standard make variable to specify flags needed by the linker.
# in particular, the -L DIR telling the linker to search DIR for libraries.
LDFLAGS =

# this is the standard make variable to specify needed libraries using -l
LDLIBS = -lm

log10:		log10.o

.PHONY:		clean
clean:
		rm -f *.o log10 *~


